apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "yurt-app-manager.fullname" . }}
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ template "yurt-app-manager.name" . }}-webhook
      namespace: {{ .Release.Namespace }}
      path: /validate-apps-openyurt-io-v1alpha1-nodepool
  admissionReviewVersions:
  - v1
  sideEffects: None
  failurePolicy: Fail
  name: vnodepool.kb.io
  rules:
  - apiGroups:
    - apps.openyurt.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - nodepools
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ template "yurt-app-manager.name" . }}-webhook
      namespace: {{ .Release.Namespace }}
      path: /validate-apps-openyurt-io-v1alpha1-uniteddeployment
  admissionReviewVersions:
  - v1
  sideEffects: None
  failurePolicy: Fail
  name: vuniteddeployment.kb.io
  rules:
  - apiGroups:
    - apps.openyurt.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - uniteddeployments
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ template "yurt-app-manager.name" . }}-webhook
      namespace: {{ .Release.Namespace }}
      path: /validate-apps-openyurt-io-v1alpha1-yurtappset
  admissionReviewVersions:
  - v1
  sideEffects: None
  failurePolicy: Fail
  name: vyurtappset.kb.io
  rules:
  - apiGroups:
    - apps.openyurt.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - yurtappsets
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ template "yurt-app-manager.name" . }}-webhook
      namespace: {{ .Release.Namespace }}
      path: /validate-apps-openyurt-io-v1alpha1-yurtappdaemon
  admissionReviewVersions:
  - v1
  sideEffects: None
  failurePolicy: Fail
  name: vyurtappdaemon.kb.io
  rules:
  - apiGroups:
    - apps.openyurt.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - yurtappdaemons
- admissionReviewVersions:
    - v1
  clientConfig:
    caBundle: Cg==
    service:
      name: {{ template "yurt-app-manager.name" . }}-webhook
      namespace: {{ .Release.Namespace }}
      path: /validate-apps-openyurt-io-v1alpha2-yurtingress
  failurePolicy: Fail
  name: vyurtingress.kb.io
  rules:
    - apiGroups:
        - apps.openyurt.io
      apiVersions:
        - v1alpha2
      operations:
        - CREATE
        - UPDATE
        - DELETE
      resources:
        - yurtingresses
  sideEffects: None
